name: Run benchmark between base branch

on:
  pull_request:
    branches:
      - "main"

jobs:
  benchmark-base:
    if: startsWith(github.head_ref, 'perf/')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.25.5
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
      - name: Run benchmark for base branch
        run: make benchmark > bench.base.txt
      - name: Upload base benchmark result
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: benchmark-base
          path: bench.base.txt
  benchmark-head:
    if: startsWith(github.head_ref, 'perf/')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.25.5
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run benchmark for head branch
        run: make benchmark > bench.head.txt
      - name: Upload base benchmark result
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: benchmark-head
          path: bench.head.txt
  compare:
    if: startsWith(github.head_ref, 'perf/')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    needs: [ benchmark-base, benchmark-head ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.25.5
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download base benchmark result
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: benchmark-base
      - name: Download head benchmark result
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: benchmark-head
      - name: Compare benchmarks and put comment
        run: |
          go run cmd/benchmark/main.go ./bench.base.txt ./bench.head.txt > comment.md
          gh pr comment ${{ github.event.number }} --body-file ./comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
